### PR TITLE
Support fot Lambda maximal segment tangent estimator

### PR DESCRIPTION
**Pull request by copyme**
As in the title. First, LMST must be merged with DGtal.

### CODE REVIEW

**Comment by JacquesOlivierLachaud** [comment]
It is good to have now 2 methods for estimating tangents along 3d curve ! The PR seems ready for merge (I will just look for some typos before). I have a question nevertheless.
When running L-MST on 6-connected curve, it works really bad. Is it expected ?
./estimators/3dCurveTangentEstimator ~/GITHUB/DGtal/examples/samples/sinus.dat -V ON -c -T 6 -m L-MST

**Comment by copyme** [comment]
@JacquesOlivierLachaud I did not work much with 6-curves but seems that for them LMST gives  meaning less results. I think that the problem is with tangential cover of 6-curves.

**Comment by JacquesOlivierLachaud** [comment]
Are you using NaiveDSSComputer when processing 6-connected curves ?

**Comment by copyme** [comment]
@JacquesOlivierLachaud Yes.

**Comment by copyme** [comment]
@JacquesOlivierLachaud I am patching this mistake.

**Comment by copyme** [comment]
@JacquesOlivierLachaud Done. To compile you need patches to DGtal from #1047.

**Comment by JacquesOlivierLachaud** [comment]
Ok. I've tester l-MST on 6-connected curve and it works nicely. Good job !
I merge.

**Pull request merged**
